version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: sls_db
      POSTGRES_USER: sls_user
      POSTGRES_PASSWORD: sls_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis Cache
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  # Scrapy Crawler
  crawler:
    build: ./crawler
    volumes:
      - ./crawler:/app
    depends_on:
      - postgres
      - redis

  # Flask Backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://sls_user:sls_password@postgres:5432/sls_db
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  # React Frontend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: